name: Install Prerequisites from git

runs:
  using: composite
  steps:
    - name: Install from git
      run: |
        git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
        git clone --quiet --depth 1 https://github.com/mapbox/protozero.git ../protozero
      shell: bash

