name: CMake

runs:
  using: composite
  steps:
    - name: Create build directory
      run: mkdir build
      shell: bash
    - name: Configure
      run: |
        cmake -LA .. \
              ${CMAKE_OPTS} \
              -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      shell: bash
      working-directory: build
